name: Deploy ACS BotFramework-WebChat Control Sample App

on:
  workflow_dispatch:
    inputs:
      orgId:
        description: 'Organization Id'
        required: false
        default: '648f001e-c749-4e02-8737-e44ded8ed759'
      orgUrl:
        description: 'Organization URL'
        require: false
        default: 'https://648f001ec7494e028737e44ded8ed759-crm.oc.crmlivetie.com'
      widgetId:
        description: 'Widget Id'
        require: false
        default: 'a35bdcb8-94d3-49a6-9970-5b3e00261250'
      email:
        description: 'Email'
        require: false
        default: 'foo@bar.com'

env:
  orgId: ${{ github.event.inputs.orgId }}
  orgUrl: ${{ github.event.inputs.orgUrl }}
  widgetId: ${{ github.event.inputs.widgetId }}
  email: ${{ github.event.inputs.email }}
  rootUrl: https://dev.edwardtran.me/omnichannel-chat-sdk/acs/botframework-webchat-control
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.X
      - name: Download omnichannel-chat-sdk
        run: |
          git clone --branch acs https://github.com/xTEddie/omnichannel-chat-sdk.git
      - name: Install NPM Packages
        working-directory: omnichannel-chat-sdk
        run: |
          npm install
      - name: Build NPM packages
        working-directory: omnichannel-chat-sdk
        run: |
          npm run build:tsc
      - name: Npm packaging
        working-directory: omnichannel-chat-sdk
        run: npm pack
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: npm-tarball
          path: '**/*.tgz'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.X
      - name: Download botframework-webchat-control
        run: |
          npx github-files-fetcher --url="https://github.com/microsoft/omnichannel-chat-sdk-samples/tree/main/botframework-webchat-control"
      - name: Install NPM Packages
        working-directory: botframework-webchat-control
        run: |
          npm install
      - uses: actions/download-artifact@v2.0.5
        with:
          name: npm-tarball
          path: omnichannel-chat-sdk/samples/botframework-webchat-control
      - name: Update @microsoft/omnichannel-chat-sdk
        working-directory: botframework-webchat-control
        run: |
          npm uninstall @microsoft/omnichannel-chat-sdk
          npm install ./**/*.tgz
      - name: Configure Environment
        working-directory: botframework-webchat-control
        run: |
          echo "# Chat Widget Config" > .env
          echo "REACT_APP_orgId='$orgId'" >> .env
          echo "REACT_APP_orgUrl='$orgUrl'" >> .env
          echo "REACT_APP_widgetId='$widgetId'" >> .env
          echo "" >> .env
          echo "# Transcript Config" >> .env
          echo "REACT_APP_email='$email'" >> .env
      - name: Set App Server Root
        working-directory: botframework-webchat-control
        run: |
          echo "$(cat package.json | jq --arg url ${rootUrl} '. + {homepage: $url}')" > package.json
      - name: Build App
        working-directory: botframework-webchat-control
        run: |
          yarn build
      - name: Configure Deployment
        run: |
          mv omnichannel-chat-sdk/samples/botframework-webchat-control tmp
          cp -r tmp/build .
          mv build botframework-webchat-control
      - name: Clean Up
        run: |
          rm -rf tmp
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: botframework-webchat-control
          target-folder: omnichannel-chat-sdk/acs/botframework-webchat-control
